version: '3'
services:
  chappie:
    build: .
    environment: []
    ports:
      - "8080:8080"
    dns:
      - 10.0.1.1
      - 10.0.1.4
      - 8.8.4.4
      - 8.8.8.8
    volumes:
      - "./data:/chappie"
    restart: unless-stopped
