version: '3'
services:
  chappie-bot:
    build: ../chappie-bot
    volumes:
      - "../chappie-bot/rasa:/app"
    restart: unless-stopped
  chappie-timeentry:
    build: ../chappie-timeentry
    volumes:
      - "../chappie-timeentry/data:/chappie"
    restart: unless-stopped
  chappie:
    build: .
    environment:
      RASA_HOST: http://chappie-bot:5005
      TIMEENTRY_HOST: http://chappie-timeentry:8089
    ports:
      - "8080:8080"
    volumes:
      - "./data:/chappie"
    restart: unless-stopped
    depends_on:
      - chappie-bot
      - chappie-timeentry
